
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://miyuywvkvxqmmhyjildf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1peXV5d3ZrdnhxbW1oeWppbGRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMTQzNjMsImV4cCI6MjA2MjY5MDM2M30.mg5h91uS3NIli5pHH4UxyXBM60gmb12T--W3_MH9bEQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
